name: Build EXE on Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install --user pyinstaller
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          }

      - name: Compiler le script
        run: |
          $env:PATH += ";$env:USERPROFILE\AppData\Roaming\Python\Python311\Scripts"
          pyinstaller --onefile --hidden-import=win32timezone main.py

      - name: Uploader l'exécutable
        uses: actions/upload-artifact@v4
        with:
          name: mon-exe-windows
          path: dist/main.exe
